---
- name: Configurer Linux client
  hosts: Linux
  become: true

  tasks:
    - name: 1. Définir les variables et l'IP autorisée
      ansible.builtin.set_fact:
        snmp_package: "{{ 'net-snmp' if ansible_os_family == 'RedHat' else 'snmpd' }}"
        applycfg_value: "{{ '1' if supervisor == 'central' else '7' }}"
        supervisor_ip: "{{ '192.168.2.3' if supervisor == 'central' else '192.168.3.2' }}"
        poller_name: "{{ 'Central' if supervisor == 'central' else 'poller' }}"

    - name: 2. Installer le paquet SNMP
      ansible.builtin.package:
        name: "{{ snmp_package }}"
        state: present

    - name: 3. Configurer le Firewall - Ouvrir le port SNMP UDP/161
      ansible.posix.firewalld:
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
        rich_rule: "rule family='ipv4' source address='{{ supervisor_ip }}' port protocol=udp port=161 accept"
      when: ansible_os_family == 'RedHat'

    - name: 3b. Configurer le Firewall - Autoriser le Ping (ICMP)
      ansible.posix.firewalld:
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
        rich_rule: "rule family='ipv4' source address='{{ supervisor_ip }}' protocol value='icmp' accept"
      when: ansible_os_family == 'RedHat'

    - name: 4. Vérifier le statut de snmpd
      ansible.builtin.service:
        name: snmpd
        state: started
        enabled: yes

    - name: 5. Deployer la configuration (snmpd.conf)
      ansible.builtin.template:
        src: snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf
        mode: '0644'
      vars:
        snmp_poller_ip: "{{ supervisor_ip }}"
      register: snmpd_conf

    - name: 6. Rédémarrer le service
      ansible.builtin.service:
        name: snmpd
        state: restarted
      when: snmpd_conf is changed

    - name: 7. Test
      ansible.builtin.command: >
        snmpget -v 2c -c {{ snmp_community_string | default('public') }}
        127.0.0.1 1.3.6.1.2.1.1.1.0
      register: result
      changed_when: false
      failed_when: "'No Response' in result.stderr"

    - name: 8. CLAPI - Ajouter/Modifier l'hôte (ADD) avec le format exact
      ansible.builtin.command: >
        /usr/share/centreon/bin/centreon -u admin -p Centreon1admin!
        -o HOST -a ADD
        -v "{{ inventory_hostname }};{{ inventory_hostname }};{{ ansible_host }};OS-Linux-SNMP-custom;{{ poller_name }};"
      delegate_to: "central"
      become: true
      register: clapi_add_result
      failed_when: >
        clapi_add_result.rc != 0
        and 'Object already exists' not in clapi_add_result.stdout
      changed_when: clapi_add_result.rc == 0

    - name: 9. CLAPI - Appliquer le template à l'hôte (APPLYTPL)
      ansible.builtin.command: >
        /usr/share/centreon/bin/centreon -u admin -p Centreon1admin!
        -o HOST -a APPLYTPL
        -v "{{ inventory_hostname }}"
      delegate_to: "central"
      become: true
      changed_when: true

    - name: 10. CLAPI - Exporter et Redémarrer le moteur de supervision
      ansible.builtin.command: >
        /usr/share/centreon/bin/centreon -u admin -p 'Centreon1admin!'
        -a APPLYCFG -v {{ applycfg_value }}
      delegate_to: "central"
      become: true
      changed_when: true