---
- name: Configurer Linux client
  hosts: linux
  become: true

  vars:
    centreon_ip: "192.168.3.2" # poller Centreon
    snmp_community: "public"
    poller_name: "poller-1"

  tasks:
    - name: 1. Définir les variables et l'IP autorisée
      ansible.builtin.set_fact:
        snmp_package: "{{ 'net-snmp' if ansible_os_family == 'RedHat' else 'snmpd' }}"

    - name: Installer le paquet SNMP
      ansible.builtin.package:
        name: "{{ snmp_package }}"
        state: present

    - name: Ouvrir le port SNMP
      ansible.posix.firewalld:
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
        rich_rule: "rule family='ipv4' source address='{{ centreon_ip }}' port protocol=udp port=161 accept"
      when: ansible_os_family == 'RedHat'

    - name: Autoriser le ping
      ansible.posix.firewalld:
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
        rich_rule: "rule family='ipv4' source address='{{ centreon_ip }}' protocol value='icmp' accept"
      when: ansible_os_family == 'RedHat'

    - name: Vérifier la présence du service snmpd
      ansible.builtin.service:
        name: snmpd
        state: started
        enabled: yes

    - name: Déployer la configuration (snmpd.conf)
      ansible.builtin.template:
        src: snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf
        mode: '0644'
      vars:
        centreon_ip: "{{ centreon_ip }}"
      register: snmpd_conf

    - name: Rédémarrer le service snmpd
      ansible.builtin.service:
        name: snmpd
        state: restarted
      when: snmpd_conf is changed