---
- name: Configurer Windows client
  hosts: windows
  gather_facts: no

  vars:
    mon_domaine_dns: "crocopik.local"
    ad_admin_user: "Administrator@crocopik.local" 
    ad_admin_password: "R00t"

    centreon_ip: "192.168.3.2" # poller Centreon
    snmp_community: "public"

  tasks:
    ##### Joindre le domaine AD #####
    # - name: Joindre le domaine
    #   microsoft.ad.membership:
    #     dns_domain_name: "{{ mon_domaine_dns }}"
    #     hostname: "{{ inventory_hostname }}"
    #     domain_admin_user: "{{ ad_admin_user }}"
    #     domain_admin_password: "{{ ad_admin_password }}"
    #     state: domain
    #   register: ad_result

    # - name: Redémarrage après jonction au domaine
    #   ansible.windows.win_reboot:
    #   when: ad_result.reboot_required

    ##### Installer et configurer SNMP #####
    - name: Configuration du service SNMP
      block:
      - name: Installer le client SNMP
        ansible.windows.win_shell: |
          $cap = Get-WindowsCapability -Online -Name "SNMP.Client~~~~0.0.1.0"
          if ($cap.State -ne "Installed") {
              Add-WindowsCapability -Online -Name "SNMP.Client~~~~0.0.1.0"
          } else {
              Write-Output "ALREADY_INSTALLED"
          }
        become: yes
        become_method: runas
        become_user: SYSTEM
        register: snmp_install_result
        changed_when: "'ALREADY_INSTALLED' not in snmp_install_result.stdout"

      - name: Configurer la Communauté SNMP
        ansible.windows.win_regedit:
          path: HKLM:\SYSTEM\CurrentControlSet\Services\SNMP\Parameters\ValidCommunities
          name: "{{ snmp_community }}"
          data: 4
          type: dword

      - name: Autoriser l'IP de Centreon
        ansible.windows.win_regedit:
          path: HKLM:\SYSTEM\CurrentControlSet\Services\SNMP\Parameters\PermittedManagers
          name: 1
          data: "{{ centreon_ip }}"
          type: string

      - name: Redémarrer le service SNMP pour appliquer les changements
        ansible.windows.win_service:
          name: SNMP
          state: restarted
          start_mode: auto
    
    ##### Installer et configurer NSClient++ #####
    - name: Installation et configuration de NSClient++
      block:
        - name: Vérifier la présence du service nscp
          ansible.windows.win_service:
            name: nscp
          register: nscp_service_info
          failed_when: false

        - name: Installation de NSClient++
          block:
            - name: Créer dossier temporaire
              ansible.windows.win_file:
                path: C:\Temp
                state: directory

            - name: Télécharger l'installeur Centreon-NSClient
              ansible.windows.win_get_url:
                url: "https://github.com/centreon/centreon-nsclient-build/releases/download/20251100/Centreon-NSClient-0.5.2.41-20251100-x64.exe"
                dest: C:\Temp\Centreon-NSCP.exe

            - name: Lancer l'installation silencieuse
              ansible.windows.win_package:
                path: C:\Temp\Centreon-NSCP.exe
                product_id: '{1B7B125C-AD5E-44B0-A48B-7FB69F04F102}'
                arguments: /S
              become: yes
              become_method: runas
              become_user: SYSTEM

            - name: Supprimer l'installeur NSClient++
              ansible.windows.win_file:
                path: C:\Temp\Centreon-NSCP.exe
                state: absent

          when: nscp_service_info.exists == false

        - name: Démarrer le service NSClient (nscp)
          ansible.windows.win_service:
            name: nscp
            state: started
            start_mode: auto

        - name: Copier le fichier nsclient.ini depuis le serveur Ansible
          ansible.windows.win_copy:
            src: nsclient.ini
            dest: "C:\\Program Files\\Centreon NSClient++\\nsclient.ini"

        - name: Redémarrer NSClient
          ansible.windows.win_service:
            name: nscp
            state: restarted

        - name: Ouvrir le port SNMP
          community.windows.win_firewall_rule:
            name: "Centreon SNMP-IN"
            localport: 161
            action: allow
            direction: in
            protocol: udp
            profiles: domain,private,public

        - name: Ouvrir les ports NSClient
          community.windows.win_firewall_rule:
            name: "Centreon NSClient-IN"
            localport: 12489,5666
            action: allow
            direction: in
            protocol: tcp
            profiles: domain,private,public

        - name: Autoriser le PING (ICMPv4)
          community.windows.win_firewall_rule:
            name: "ICMP-IN (Ping)"
            action: allow
            direction: in
            protocol: icmpv4
            profiles: domain,private,public

        - name: Copier le fichier check_disk.ps1 depuis le serveur Ansible
          ansible.windows.win_copy:
            src: check_disk.ps1
            dest: "C:\\Program Files\\Centreon NSClient++\\scripts\\check_disk.ps1"